Repository CHaiz15/Rancid-Tomatillos, pull requests merged in 2020-02, with the labels that each got.

#1 Component setups
  src/App.js
  src/App/App.js
  src/App/App.scss
  src/App/App.test.js
  src/MovieThumbnail/MovieThumbnail.js
  src/MovieThumbnail/MovieThumbnail.scss
  src/MovieThumbnail/MovieThumbnail.test.js
  src/MoviesPage/MoviesPage.js
  src/MoviesPage/MoviesPage.scss
  src/MoviesPage/MoviesPage.test.js
  src/index.js
  src/logo.svg
Labels: enhancement

#3 Movies display
  src/Actions/index.js
  src/App/App.js
  src/App/App.scss
  src/MovieThumbnail/MovieThumbnail.js
  src/MoviesPage/MoviesPage.js
  src/MoviesPage/MoviesPage.scss
  src/Reducers/index.js
  src/Reducers/moviesReducer.js
  src/Reducers/userReducer.js
  src/assets/film-bg.jpg
  src/assets/film-icon.svg
  src/index.scss
Labels: enhancement

#4 Movie details display
  src/App/App.js
  src/App/App.scss
  src/MovieDetails/MovieDetails.js
  src/MovieDetails/MovieDetails.scss
  src/MoviesPage/MoviesPage.js
Labels: enhancement

#6 Ratings progress
  src/Actions/index.js
  src/Login/Login.js
  src/Login/Login.scss
  src/MovieThumbnail/MovieThumbnail.js
  src/MoviesPage/MoviesPage.js
  src/Reducers/userReducer.js
  src/apiCalls.js
  src/assets/theatre-bg.jpg
Labels: enhancement

#7 Ratings progress
  src/Actions/index.js
  src/Login/Login.js
  src/MovieDetails/MovieDetails.js
  src/Reducers/index.js
  src/Reducers/ratingsReducer.js
  src/Reducers/userReducer.js
Labels: enhancement

#8 Api calls testing
  package-lock.json
  package.json
  src/App/App.js
  src/Login/Login.test.js
  src/Login/__snapshots__/Login.test.js.snap
  src/apiCalls.js
  src/apiCalls.test.js
Labels: help wanted

#9 Redux tests
  src/Actions/actions.test.js
  src/Actions/index.js
  src/App/App.js
  src/Login/Login.js
  src/MovieDetails/MovieDetails.js
  src/MovieThumbnail/MovieThumbnail.js
  src/Reducers/moviesReducer.js
  src/Reducers/moviesReducer.test.js
  src/Reducers/ratingsReducer.test.js
  src/Reducers/userReducer.test.js
  src/apiCalls.js
  src/apiCalls.test.js
Labels: enhancement, test

#10 Styling layout
  public/favicon.ico
  public/index.html
  src/App/App.js
  src/App/App.scss
  src/MovieDetails/MovieDetails.js
  src/MovieDetails/MovieDetails.scss
  src/MovieThumbnail/MovieThumbnail.js
  src/MovieThumbnail/MovieThumbnail.scss
  src/MoviesPage/MoviesPage.scss
  src/index.scss
Labels: enhancement

#12 Ratings func
  src/MovieDetails/MovieDetails.js
  src/MovieDetails/MovieDetails.scss
  src/MovieThumbnail/MovieThumbnail.js
  src/apiCalls.js
Labels: bug, enhancement

#13 Update ratings
  src/MovieDetails/MovieDetails.js
  src/MovieDetails/MovieDetails.scss
  src/apiCalls.js
Labels: enhancement

#15 Styling additions
  src/App/App.scss
  src/Login/Login.js
  src/Login/Login.scss
  src/Login/__snapshots__/Login.test.js.snap
  src/MovieDetails/MovieDetails.js
  src/MovieDetails/MovieDetails.scss
  src/MovieThumbnail/__snapshots__/MovieThumbnail.test.js.snap
Labels: enhancement

#16 Component proptypes
  src/Login/Login.js
  src/MovieDetails/MovieDetails.js
  src/MovieThumbnail/MovieThumbnail.js
  src/MoviesPage/MoviesPage.js
Labels: enhancement

#17 Testing movie details
  src/App/App.test.js
  src/App/__snapshots__/App.test.js.snap
  src/MovieDetails/MovieDetails.test.js
  src/MovieDetails/__snapshots__/MovieDetails.test.js.snap
  src/apiCalls.test.js
Labels: enhancement
